require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.catppuccin")
require("core.plugin_config.gitsigns")
require('core.plugin_config.lspkind')
require('core.plugin_config.line')
require('core.plugin_config.autotag')
require('core.plugin_config.luasnip')
require("core.plugin_config.completions")

require("core.plugin_config.lsp_config")
require("core.plugin_config.mason")
