require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.toggleterm")
require("core.plugin_config.completions")
require("core.plugin_config.lsp_config")
require("core.plugin_config.gitsigns")
-- require("core.plugin_config.copilot")
require("core.plugin_config.mason")
require("core.plugin_config.catppuccin")
require('core.plugin_config.null-ls')
require('core.plugin_config.prettier')
require('core.plugin_config.lspkind')
-- require('core.plugin_config.clangd')
require('core.plugin_config.dap')
